import { Metadata } from "next";

export const metadata: Metadata = {
   title: 'Profile',
   description: 'Generated by Next.js',
}

export default async function ProfileLayout({
   children,
}: {
   children: React.ReactNode
}) {

   return (
      <>
         {children}
      </>
   )
}
