export const metadata = {
   title: 'Error',
   description: 'Generated by Next.js',
}

export default function ErrorLayout({
   children,
}: {
   children: React.ReactNode
}) {
   return (
      <>
         {children}
      </>
   )
}
